behaviors:
  MyBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 204800
      learning_rate: 0.00005
      beta: 0.015
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: fully_connected
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 6
    checkpoint_interval: 30000000
    max_steps: 180000000
    time_horizon: 1000
    summary_freq: 50000

