behaviors:
  MyBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 204800
      learning_rate: 0.000005
      beta: 0.015
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: fully_connected
    reward_signals:
      extrinsic: 
        strength: 0.9
        gamma: 0.995
      gail:
        strength: 0.1
        gamma: 0.8
        use_actions: true
        demo_path: Assets/ML-Agents/StrokeAvatar/ExpertDemos/ExampleDemo.demo
        use_vail: true
        learning_rate: 0.00001
    behavioral_cloning:
      demo_path: Assets/ML-Agents/StrokeAvatar/ExpertDemos/ExampleDemo.demo
      strength: 0.2
      steps: 5000000
    keep_checkpoints: 120
    checkpoint_interval: 1000000
    max_steps: 120000000
    time_horizon: 1000
    summary_freq: 50000

# environment_parameters:
#   my_environment_parameter:
#     curriculum:
#       - name: Lesson1
#         completion_criteria:
#           measure: reward
#           behavior: MyBehavior
#           signal_smoothing: true
#           min_lesson_length: 500
#           threshold: 280
#         value: 0
#       - name: Lesson2
#         completion_criteria:
#           measure: reward
#           behavior: MyBehavior
#           signal_smoothing: true
#           min_lesson_length: 500
#           threshold: 280
#           require_reset: true
#         value: 0.1875
#       - name: Lesson3
#         completion_criteria:
#           measure: reward
#           behavior: MyBehavior
#           signal_smoothing: true
#           min_lesson_length: 500
#           threshold: 280
#           require_reset: true
#         value: 0.375
#       - name: Lesson4
#         completion_criteria:
#           measure: reward
#           behavior: MyBehavior
#           signal_smoothing: true
#           min_lesson_length: 500
#           threshold: 280
#           require_reset: true
#         value: 0.5625
#       - name: Lesson5
#         value: 0.75
